name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests and Lint
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - run: make test

      - name: make lint
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          skip-build-cache: true
          skip-pkg-cache: true

      - name: coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.txt
